update

diff --git a/.github/workflows/run_ci.yml b/.github/workflows/run_ci.yml
--- a/.github/workflows/run_ci.yml
+++ b/.github/workflows/run_ci.yml
@@ -34,34 +34,34 @@ jobs:
           packer build wp.pkr.hcl >> build.log 2>&1
         continue-on-error: true
 
-      - name: get actions status
-        id: get_status
-        run: |
-          PACKER_INIT_STATUS=$([[ '${{ steps.packer_init.outcome }}' == 'success' ]] && echo 'Собрано ✅' || echo 'Всё, конец ... ❌')
-          echo "PACKER_INIT_STATUS=${PACKER_INIT_STATUS//[$'\n']/ }" >> $GITHUB_ENV  # Заменить новые строки
-          
-          PACKER_BUILD_STATUS=$([[ '${{ steps.packer_build.outcome }}' == 'success' ]] && echo 'Собрано ✅' || echo 'Всё, конец ... ❌')
-          echo "PACKER_BUILD_STATUS=${PACKER_BUILD_STATUS//[$'\n']/ }" >> $GITHUB_ENV  # Заменить новые строки
-          
-          # Если один из шагов не успешен, выводим ошибку
-          if [[ '${{ steps.packer_init.outcome }}' != 'success' ]]; then
-            echo "PACKER_INIT_ERROR=$(cat packer/init.log | tr -d '\n')" >> $GITHUB_ENV  # Убираем новые строки из лога
-          fi
-          
-          if [[ '${{ steps.packer_build.outcome }}' != 'success' ]]; then
-            echo "PACKER_BUILD_ERROR=$(cat packer/build.log | tr -d '\n')" >> $GITHUB_ENV  # Убираем новые строки из лога
-          fi
+#      - name: get actions status
+#        id: get_status
+#        run: |
+#          PACKER_INIT_STATUS=$([[ '${{ steps.packer_init.outcome }}' == 'success' ]] && echo 'Собрано ✅' || echo 'Всё, конец ... ❌')
+#          echo "PACKER_INIT_STATUS=${PACKER_INIT_STATUS//[$'\n']/ }" >> $GITHUB_ENV  # Заменить новые строки
+#
+#          PACKER_BUILD_STATUS=$([[ '${{ steps.packer_build.outcome }}' == 'success' ]] && echo 'Собрано ✅' || echo 'Всё, конец ... ❌')
+#          echo "PACKER_BUILD_STATUS=${PACKER_BUILD_STATUS//[$'\n']/ }" >> $GITHUB_ENV  # Заменить новые строки
+#
+#          # Если один из шагов не успешен, выводим ошибку
+#          if [[ '${{ steps.packer_init.outcome }}' != 'success' ]]; then
+#            echo "PACKER_INIT_ERROR=$(cat packer/init.log | tr -d '\n')" >> $GITHUB_ENV  # Убираем новые строки из лога
+#          fi
+#
+#          if [[ '${{ steps.packer_build.outcome }}' != 'success' ]]; then
+#            echo "PACKER_BUILD_ERROR=$(cat packer/build.log | tr -d '\n')" >> $GITHUB_ENV  # Убираем новые строки из лога
+#          fi
 
-      - name: TG Notification
-        if: always()
-        env:
-          TG_TOKEN: ${{ secrets.TG_TOKEN }}
-          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
-        run: |
-          MESSAGE="Build status💬:
-          *Packer init status*: $PACKER_INIT_STATUS
-          *Packer build status*: $PACKER_BUILD_STATUS"
-          curl -s -X POST https://api.telegram.org/bot${{ env.TG_TOKEN }}/sendMessage \
-          -d chat_id=${{ env.TG_CHAT_ID }} \
-          -d parse_mode=Markdown \
-          -d text="$MESSAGE"
+#      - name: TG Notification
+#        if: always()
+#        env:
+#          TG_TOKEN: ${{ secrets.TG_TOKEN }}
+#          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
+#        run: |
+#          MESSAGE="Build status💬:
+#          *Packer init status*: $PACKER_INIT_STATUS
+#          *Packer build status*: $PACKER_BUILD_STATUS"
+#          curl -s -X POST https://api.telegram.org/bot${{ env.TG_TOKEN }}/sendMessage \
+#          -d chat_id=${{ env.TG_CHAT_ID }} \
+#          -d parse_mode=Markdown \
+#          -d text="$MESSAGE"
